{
 "title": "TRVs Overview",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Room Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "room_temperature_celsius", "legendFormat": "{{trv}}" }
   ]
  },
  {
   "title": "Radio Signal Strength Indicator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    { "expr": "radio_rssi_dbm", "legendFormat": "{{trv}}" }
   ]
  },
  {
   "title": "Number of TRVs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "recent_reporting_trv_count" }
   ]
  },
  {
   "title": "Missed Messages (per hour)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(messages_missed_total[5m])*3600.0",
     "legendFormat": "{{trv}}"
    }
   ]
  },
  {
   "title": "Lowest battery voltages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bottomk(5, battery_volts)", "legendFormat": "{{trv}}" }
   ]
  },
  {
   "title": "Received Messages (per Hour)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(messages_received_total[15m])*3600.0",
     "legendFormat": "{{trv}}"
    }
   ]
  }
 ]
}