{
 "title": "TRV Detail",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "TRV",
    "query": {
     "query": "label_values(last_message_timestamp, trv)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperatures and Valve",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "room_temperature_celsius{trv=\"$TRV\"}",
     "legendFormat": "{{trv}} temp"
    },
    {
     "expr": "target_temperature_celsius{trv=\"$TRV\"}",
     "legendFormat": "{{trv}} target"
    },
    {
     "expr": "valve_open_ratio{trv=\"$TRV\"}",
     "legendFormat": "{{trv}} valve"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "relative_humidity_ratio{trv=\"$TRV\"}*100.0",
     "legendFormat": "{{trv}}"
    }
   ]
  },
  {
   "title": "TRV Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "call_for_heat{trv=\"$TRV\"}",
     "legendFormat": "{{trv}} CFH"
    },
    {
     "expr": "light_level_ratio{trv=\"$TRV\"}",
     "legendFormat": "{{trv}} light"
    },
    {
     "expr": "occupancy1{trv=\"$TRV\"}",
     "legendFormat": "{{trv}} occ1"
    },
    {
     "expr": "occupancy2{trv=\"$TRV\"}",
     "legendFormat": "{{trv}} occ2"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "battery_volts{trv=\"$TRV\"}",
     "legendFormat": "{{trv}}"
    }
   ]
  },
  {
   "title": "Radio Received Signal Strength",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "expr": "radio_rssi_dbm{trv=\"$TRV\"}",
     "legendFormat": "{{trv}} RSSI"
    }
   ]
  },
  {
   "title": "Valve motion",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cumulative_valve_total{trv=\"$TRV\"}[20m])*3600",
     "legendFormat": "{{trv}}"
    }
   ]
  },
  {
   "title": "Missed Messages (per hour)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(messages_missed_total{trv=\"$TRV\"}[20m])*3600.0",
     "legendFormat": "{{trv}}"
    }
   ]
  }
 ]
}